- hosts: mongodb
  vars_prompt:
    - name: "mongodb_username"
      prompt: "Enter new username for MongoDB"
      private: no
    - name: "mongodb_password"
      prompt: "Enter new password for MongoDB"
  remote_user: root
  become: yes
  tasks:
  - name: Installing Dependencies
    apt: 
      name: gnupg
      state: latest
  - name: Dependencies (cont. 1) Installing PyMongo
    apt:
      pkg:
        - python-dev
        - python-pip
        - python-setuptools
  - name: Dependencies (cont. 2) PIP installing
    pip:
      name: pymongo
      
  - name: Adding MongoDB Key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.2.asc
      state: present
  - name: Adding MongoDB Repository
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 main
      state: present
  - name: Installing MongoDB Packages
    apt:
      pkg:
      - mongodb-org=4.2.2
      - mongodb-org-server=4.2.2
      - mongodb-org-shell=4.2.2
      - mongodb-org-mongos=4.2.2
      - mongodb-org-tools=4.2.2
  - name: Enable and Start MongoDB Systemd
    systemd:
      state: started
      name: mongod
      enabled: yes
      masked: no

  - name: Create administrative user '{{ mongodb_username }}' 
    mongodb_user:
      database: admin
      name: '{{ mongodb_username }}'
      password: '{{ mongodb_password }}'
      roles: root
      state: present